//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contensive.Addons.Menuing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contensive.Addons.Menuing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- nav within navbar --&gt;
        ///&lt;button class=&quot;navbar-toggler&quot; type=&quot;button&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#navbarNavDropdown{{menuId}}&quot; aria-controls=&quot;navbarNavDropdown{{menuId}}&quot; aria-expanded=&quot;false&quot; aria-label=&quot;Toggle navigation&quot;&gt;
        ///	&lt;span class=&quot;navbar-toggler-icon&quot;&gt;&lt;/span&gt;
        ///&lt;/button&gt;
        ///&lt;div class=&quot;{{classTopWrapper}}&quot; id=&quot;navbarNavDropdown{{menuId}}&quot;&gt;
        ///	&lt;!-- nav menu pages --&gt;
        ///	&lt;ul id=&quot;{{topListHtmlId}}&quot; class=&quot; {{classTopList}}&quot;&gt;
        ///		{{#topList}}
        ///		{{#hasChildItems}}
        ///		&lt;li id=&quot;{{topItemHtmlId}}&quot; cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BootstrapNav40Layout {
            get {
                return ResourceManager.GetString("BootstrapNav40Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- li list within navbar --&gt;
        ///		{{#topList}}
        ///		{{#hasChildItems}}
        ///		&lt;li id=&quot;{{topItemHtmlId}}&quot; class=&quot;nav-item {{classTopItem}} {{classTopItemActive}} {{classItemDraggable}} {{classTopItemDropdown}}&quot;&gt;
        ///			&lt;a class=&quot;nav-link dropdown-toggle {{classTopItemAnchor}}&quot; href=&quot;{{topItemHref}}&quot; id=&quot;navbarDropdownMenuLink{{topItemPageId}}&quot; data-toggle=&quot;dropdown&quot; aria-haspopup=&quot;true&quot; aria-expanded=&quot;false&quot;&gt;{{topItemName}}&lt;/a&gt;
        ///			&lt;div class=&quot;dropdown-menu&quot; aria-labelledby=&quot;navbarDropdownMenuLink{{topItemPageId}}&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NavbarLiListLayout {
            get {
                return ResourceManager.GetString("NavbarLiListLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- li list within navbar --&gt;
        ///	&lt;ul id=&quot;{{topListHtmlId}}&quot; class=&quot; {{classTopList}}&quot;&gt;
        ///		{{#topList}}
        ///		{{#hasChildItems}}
        ///		&lt;li id=&quot;{{topItemHtmlId}}&quot; class=&quot;nav-item {{classTopItem}} {{classTopItemActive}} {{classItemDraggable}} {{classTopItemDropdown}}&quot;&gt;
        ///			&lt;a class=&quot;nav-link dropdown-toggle {{classTopItemAnchor}}&quot; href=&quot;{{topItemHref}}&quot; id=&quot;navbarDropdownMenuLink{{topItemPageId}}&quot; data-toggle=&quot;dropdown&quot; aria-haspopup=&quot;true&quot; aria-expanded=&quot;false&quot;&gt;{{topItemName}}&lt;/a&gt;
        ///			&lt;div class=&quot;dropdown-menu&quot; ari [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NavbarULLayout {
            get {
                return ResourceManager.GetString("NavbarULLayout", resourceCulture);
            }
        }
    }
}
